### PR TITLE
Fix: Xcode 11.4+ fail to build this package

### PR DESCRIPTION
**Pull request by ddddxxx**
For some reason a file named `Empty.swift` result in build failure in Xcode 11.4+.

### CODE REVIEW

**Review by luoxiu — APPROVED** [review]
wtf

**Comment by ddddxxx** [comment]
@luoxiu can we tag a new version? @FranzBusch and I really need these updates.

**Comment by ddddxxx** [comment]
I just cut [version-0.2.1 branch](https://github.com/cx-org/CombineX/tree/version-0.2.1).

**Comment by luoxiu** [comment]
Sure! Thank you very, very much for all you've done over the past few months. 
You're the hero. @ddddxxx

**Pull request merged**
