### PR TITLE
update supported platform

### LINKED ISSUE #2: Why requires macOS 10.12?
I've changed supported platform to `.macOS(.v10_10)` and everything works just fine.

### PR DESCRIPTION
**Pull request by ddddxxx**
resolve #2

### CODE REVIEW

**Comment by luoxiu** [comment]
@ddddxxx Thanks! 
Could you also update `CombineX.swift.podspec` for cocoapods users and `Build Settings -> Deployment` of `CombineX.xcodeproj` for Carthage users?

**Comment by ddddxxx** [comment]
Can I just `$ swift package generate-xcodeproj` for Carthage?

**Comment by ddddxxx** [comment]
The Carthage project seems broken to me. I just update deployment target anyway...

**Comment by luoxiu** [comment]
Looks great!

**Pull request merged**
