### PR TITLE
Cocoapods fixes

### PR DESCRIPTION
**Pull request by danielvera64**

### CODE REVIEW

**Review by ddddxxx — APPROVED** [review]
LGTM

**Comment by danielvera64** [comment]
Thanks! Can you merge it, please?

**Comment by ddddxxx** [comment]
It seems @luoxiu has not been available for a while. I'll just merge it, but I'm not able to publish updates to cocoapods.org.

**Comment by ddddxxx** [comment]
CocoaPods integration issue is tracked at #112

**Pull request merged**
