### PR TITLE
Fix observable object

### PR DESCRIPTION
**Pull request by ddddxxx**

### CODE REVIEW

**Review by luoxiu — APPROVED** [review]
Cool, cool, cool!

**Comment by luoxiu** [comment]
I don't have enough knowledge to review this pr, but since it works as expected:
Awesome!

**Comment by broadwaylamb** [comment]
This implementation looks so, so familiar to me. I swear I’ve seen it [somewhere else](https://github.com/broadwaylamb/OpenCombine/pull/93).

Folks, the MIT license doesn’t mean you can take someone else’s code, rename the variables, and pretend that you wrote it. This is just not right.

**Comment by ddddxxx** [comment]
@broadwaylamb Yes, you can see it [elsewhere](https://github.com/wickwirew/Runtime/blob/master/Sources/Runtime/Metadata/NominalMetadataType.swift), but not [there](https://github.com/broadwaylamb/OpenCombine/pull/93).

I strip a minimal implementation required for `ObservableObject` from [Runtime](https://github.com/wickwirew/Runtime) so we don't need direct Runtime dependency.

I admit we need to express the dependency of Runtime explicitly since it's not implied by SwiftPM.

Edit: Sorry i forgot test suit. I did reference OpenCombine's test cases. It's far from "take someone else’s code, rename the variables, and pretend that I wrote it", and it does't constitute copyright infringement.

> Copyright protects the particular way an author has expressed himself. It does not extend to any ideas, systems, or factual information conveyed in the work.

Anyway, thanks @broadwaylamb reminds me test resilient classes.

**Pull request merged**
