### PR TITLE
Optional and Result operator specialization

### LINKED ISSUE #22: Optional and Result operator specialization
`Optional.CX.Publisher` and `Result.CX.Publisher` have special operator overloads which returns `Optional.CX.Publisher` and `Result.CX.Publisher`.

### PR DESCRIPTION
**Pull request by ddddxxx**
resolve #22

### CODE REVIEW

**Comment by luoxiu** [comment]
@ddddxxx I finally know what you mean in #22. 😆
These methods were here before, and were removed because Combine removed them.

**Comment by ddddxxx** [comment]
You can use these methods but their definition do not appear in Combine's header. thats odd.
image

When you ⌘Click, Xcode is confused about their definition.
image

The first one lead you to Combine's header without specific position.

**Comment by ddddxxx** [comment]
Leave the definition magic aside, I think we should implement these methods anyway, or we get inconsistent behavior.

**Comment by luoxiu** [comment]
> Leave the definition magic aside, I think we should implement these methods anyway, or we get inconsistent behavior.

OK, that makes sesnse.

**Pull request merged**
