### PR TITLE
Add versioning tests

### PR DESCRIPTION
**Pull request by ddddxxx**
Combine's behavior changes over time. Our test suit should adapt for system version.

Our test suit was broken due to [the updates to macOS virtual environment of GitHub Action](https://github.blog/changelog/2020-01-09-github-actions-updates-to-the-macos-10-15-virtual-environment/). This pr is not intended to fix the actual behavior, just make the test suit pass against Combine.

### CODE REVIEW

**Comment by ddddxxx** [comment]
It can be merged since I only change the test suit to match Combine's behavior. The actual implementation should update accordingly.

**Comment by luoxiu** [comment]
Some ci tasks have failed. Do you want to run them again?

**Comment by ddddxxx** [comment]
The CI against Combine is cancelled because CombineX fail the test 🤔.

**Comment by ddddxxx** [comment]
@luoxiu Done, Combine passed the CI.

**Review by luoxiu — DISMISSED** [review]

**Comment by luoxiu** [comment]
Failed on Linux...

**Comment by ddddxxx** [comment]
@luoxiu Linux tests (against CombineX) failed as expected. CombineX currently is out of sync with Combine.

> This pr is not intended to fix the actual behavior, just make the test suit pass against Combine.

**Comment by luoxiu** [comment]
ok...

**Review by luoxiu — DISMISSED** [review]

**Comment by ddddxxx** [comment]
OK I just disable all the failing tests and mark them with "// FIXME: Versioning:".

**Comment by ddddxxx** [comment]
@luoxiu sorry for disturbing you again 😅, please review and merge.

**Review by luoxiu — APPROVED** [review]

**Pull request merged**
